import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const API = (import.meta.env.VITE_API_URL || 'http://localhost:8080/api').replace(/\/$/, '')

async function api(path, options = {}) {
  const res = await fetch(`${API}${path}`, {
    headers: { 'Content-Type': 'application/json', ...(options.headers || {}) },
    ...options
  })
  const text = await res.text()
  let data = null
  try { data = text ? JSON.parse(text) : null } catch { data = text }
  if (!res.ok) throw new Error(data?.message || data?.error || `Request failed (${res.status})`)
  return data
}

const emptyBook = { title:'', author:'', isbn:'', category:'', totalCopies:1, availableCopies:1, shelfLocation:'' }
const emptyUser = { name:'', email:'', password:'', role:'STUDENT', active:true }

function Login({ onLogin }) {
  const [email,setEmail]=useState('admin@aclibrary.test'); const [password,setPassword]=useState('Admin@123'); const [role,setRole]=useState('ADMIN'); const [captcha,setCaptcha]=useState(''); const [code,setCode]=useState(() => Math.random().toString(36).slice(2,7).toUpperCase()); const [error,setError]=useState('')
  const submit=async e=>{e.preventDefault();setError('');if(captcha!==code){setError('Invalid CAPTCHA');return}try{const u=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password,role})});onLogin(u)}catch(err){setError(err.message)}}
  return <div className="login-page"><div className="login-card"><div className="brand">AC <span>LIBRARY SERVICES</span></div><h1>Library Management System</h1><p className="muted">Full Stack Java • React • Spring Boot • MySQL</p><form onSubmit={submit}>
    <label>Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label>
    <label>Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>
    <label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="ADMIN">Administrator</option><option value="STAFF">Library Staff</option><option value="STUDENT">Student</option></select></label>
    <div className="captcha"><strong>{code}</strong><button type="button" className="ghost" onClick={()=>setCode(Math.random().toString(36).slice(2,7).toUpperCase())}>↻</button></div>
    <label>Enter CAPTCHA<input value={captcha} onChange={e=>setCaptcha(e.target.value.toUpperCase())} required/></label>
    {error && <div className="error">{error}</div>}<button className="primary full">Login</button>
  </form><div className="demo">Demo: admin@aclibrary.test / Admin@123</div></div></div>
}

function App(){
 const [user,setUser]=useState(()=>{try{return JSON.parse(localStorage.getItem('ac_user'))}catch{return null}})
 if(!user) return <Login onLogin={u=>{localStorage.setItem('ac_user',JSON.stringify(u));setUser(u)}}/>
 return <Dashboard user={user} logout={()=>{localStorage.removeItem('ac_user');setUser(null)}}/>
}

function Dashboard({user,logout}){
 const [tab,setTab]=useState('dashboard'); const [books,setBooks]=useState([]); const [users,setUsers]=useState([]); const [requests,setRequests]=useState([]); const [issues,setIssues]=useState([]); const [fines,setFines]=useState([]); const [payments,setPayments]=useState([]); const [error,setError]=useState('')
 const load=async()=>{try{setError('');const [b,u,r,i,f,p]=await Promise.all([api('/books'),api('/users'),api('/requests'),api('/issues'),api('/fines'),api('/payments')]);setBooks(b);setUsers(u);setRequests(r);setIssues(i);setFines(f);setPayments(p)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 const counts=useMemo(()=>({books:books.length,users:users.length,available:books.reduce((s,b)=>s+(b.availableCopies||0),0),requests:requests.filter(r=>r.status==='PENDING').length}),[books,users,requests])
 const create=async(path,body)=>{await api(path,{method:'POST',body:JSON.stringify(body)});load()}; const update=async(path,body)=>{await api(path,{method:'PUT',body:JSON.stringify(body)});load()}; const del=async path=>{if(confirm('Delete this record?')){await api(path,{method:'DELETE'});load()}}
 const nav=(id,label,roles)=>roles.includes(user.role)&&<button className={tab===id?'nav active':'nav'} onClick={()=>setTab(id)}>{label}</button>
 return <div className="app"><header><div className="brand">AC <span>LIBRARY SERVICES</span></div><div className="header-right"><span>{user.name} · {user.role}</span><button className="logout" onClick={logout}>Logout</button></div></header><div className="layout"><aside>{nav('dashboard','Dashboard',['ADMIN','STAFF','STUDENT'])}{nav('books','Books',['ADMIN','STAFF','STUDENT'])}{nav('users','Users',['ADMIN'])}{nav('requests','Requests',['ADMIN','STAFF','STUDENT'])}{nav('issues','Issues / Returns',['ADMIN','STAFF'])}{nav('fines','Fines',['ADMIN','STAFF','STUDENT'])}{nav('payments','Payments',['ADMIN','STAFF','STUDENT'])}</aside><main>{error&&<div className="error banner">{error}</div>}{tab==='dashboard'&&<DashboardHome counts={counts} user={user}/>} {tab==='books'&&<Books books={books} user={user} create={create} update={update} del={del}/>} {tab==='users'&&<Users users={users} create={create} update={update} del={del}/>} {tab==='requests'&&<Requests requests={requests} books={books} users={users} user={user} create={create} update={update} del={del}/>} {tab==='issues'&&<Issues issues={issues} users={users} books={books} user={user} create={create} update={update} del={del}/>} {tab==='fines'&&<Fines fines={fines} users={users} books={books} user={user} create={create} update={update} del={del}/>} {tab==='payments'&&<Payments payments={payments} fines={fines} users={users} user={user} create={create} update={update} del={del}/>}</main></div></div>
}

function Page({title,children,action}){return <><div className="page-title"><div><h2>{title}</h2><p className="muted">Manage records with CRUD operations</p></div>{action}</div>{children}</>}
function DashboardHome({counts,user}){return <Page title={`Welcome, ${user.name}`}><div className="cards"><div><small>Books</small><b>{counts.books}</b></div><div><small>Available Copies</small><b>{counts.available}</b></div><div><small>Members</small><b>{counts.users}</b></div><div><small>Pending Requests</small><b>{counts.requests}</b></div></div><div className="panel"><h3>Project workflow</h3><p>Student searches → requests → Library Staff approves/issues → book is returned → due date and fine are calculated → payment is recorded.</p><p className="muted">Database: Aiven MySQL · Backend: Spring Boot REST API · Frontend: React + CSS</p></div></Page>}

function Books({books,user,create,update,del}){const [form,setForm]=useState(emptyBook);const [edit,setEdit]=useState(null);const [q,setQ]=useState('');const canEdit=user.role==='ADMIN';const visible=books.filter(b=>(b.title+b.author+b.isbn+b.category).toLowerCase().includes(q.toLowerCase()));const save=async e=>{e.preventDefault();if(edit)await update(`/books/${edit}`,form);else await create('/books',form);setForm(emptyBook);setEdit(null)};return <Page title="Books" action={canEdit&&<button className="primary" onClick={()=>{setEdit(null);setForm(emptyBook)}}>+ Add Book</button>}><input className="search" placeholder="Search title, author, ISBN or category" value={q} onChange={e=>setQ(e.target.value)}/>{canEdit&&<form className="form-grid panel" onSubmit={save}>{['title','author','isbn','category','shelfLocation'].map(k=><input key={k} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} required={['title','author','isbn'].includes(k)}/>)}<input type="number" min="0" placeholder="totalCopies" value={form.totalCopies} onChange={e=>setForm({...form,totalCopies:+e.target.value})}/><input type="number" min="0" placeholder="availableCopies" value={form.availableCopies} onChange={e=>setForm({...form,availableCopies:+e.target.value})}/><button className="primary">{edit?'Update':'Create'}</button>{edit&&<button type="button" className="ghost" onClick={()=>{setEdit(null);setForm(emptyBook)}}>Cancel</button>}</form>}<Table headers={['Title','Author','ISBN','Category','Available','Shelf','Actions']} rows={visible.map(b=>[b.title,b.author,b.isbn,b.category,`${b.availableCopies}/${b.totalCopies}`,b.shelfLocation,canEdit?<><button className="small" onClick={()=>{setEdit(b.id);setForm(b)}}>Edit</button> <button className="small danger" onClick={()=>del(`/books/${b.id}`)}>Delete</button></>:<span>View</span>])}/></Page>}

function Users({users,create,update,del}){const [form,setForm]=useState(emptyUser);const [edit,setEdit]=useState(null);const save=async e=>{e.preventDefault();if(edit)await update(`/users/${edit}`,form);else await create('/users',form);setForm(emptyUser);setEdit(null)};return <Page title="Users" action={<button className="primary" onClick={()=>{setEdit(null);setForm(emptyUser)}}>+ Add User</button>}><form className="form-grid panel" onSubmit={save}><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input placeholder="Password" type="password" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})} required={!edit}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="ADMIN">ADMIN</option><option value="STAFF">STAFF</option><option value="STUDENT">STUDENT</option></select><select value={form.active?'true':'false'} onChange={e=>setForm({...form,active:e.target.value==='true'})}><option value="true">Active</option><option value="false">Disabled</option></select><button className="primary">{edit?'Update':'Create'}</button>{edit&&<button type="button" className="ghost" onClick={()=>{setEdit(null);setForm(emptyUser)}}>Cancel</button>}</form><Table headers={['Name','Email','Role','Status','Actions']} rows={users.map(u=>[u.name,u.email,u.role,u.active?'Active':'Disabled',<><button className="small" onClick={()=>{setEdit(u.id);setForm({...u,password:''})}}>Edit</button> <button className="small danger" onClick={()=>del(`/users/${u.id}`)}>Delete</button></>])}/></Page>}

function Requests({requests,books,users,user,create,update,del}){const students=users.filter(u=>u.role==='STUDENT');const [bookId,setBookId]=useState('');const [studentId,setStudentId]=useState(user.role==='STUDENT'?user.id:'');const request=async()=>{if(bookId&&studentId)await create('/requests',{bookId:+bookId,studentId:+studentId,status:'PENDING',requestedAt:new Date().toISOString()})};const rows=requests.filter(r=>user.role==='STUDENT'?r.studentId===user.id:true).map(r=>[r.id,r.bookTitle||r.book?.title,r.studentName||r.student?.name,r.status,new Date(r.requestedAt).toLocaleDateString(),user.role!=='STUDENT'?<><button className="small" onClick={()=>update(`/requests/${r.id}`,{...r,status:'APPROVED'})}>Approve</button> <button className="small danger" onClick={()=>update(`/requests/${r.id}`,{...r,status:'REJECTED'})}>Reject</button></>:<button className="small danger" onClick={()=>del(`/requests/${r.id}`)}>Cancel</button>]);return <Page title="Book Requests">{user.role==='STUDENT'&&<div className="panel inline-form"><select value={bookId} onChange={e=>setBookId(e.target.value)}><option value="">Select available book</option>{books.filter(b=>b.availableCopies>0).map(b=><option key={b.id} value={b.id}>{b.title} — {b.author}</option>)}</select><button className="primary" onClick={request}>Request Book</button></div>}<Table headers={['ID','Book','Student','Status','Requested','Actions']} rows={rows}/></Page>}

function Issues({issues,users,books,user,create,update,del}){const [form,setForm]=useState({bookId:'',studentId:'',issueDate:new Date().toISOString().slice(0,10),dueDate:''});const issue=async e=>{e.preventDefault();await create('/issues',{...form,bookId:+form.bookId,studentId:+form.studentId});setForm({...form,bookId:'',studentId:''})};const rows=issues.map(i=>[i.id,i.bookTitle||i.book?.title,i.studentName||i.student?.name,i.issueDate,i.dueDate,i.returnDate||'Issued',!i.returnDate?<button className="small" onClick={()=>update(`/issues/${i.id}`,{...i,returnDate:new Date().toISOString().slice(0,10)})}>Return</button>:<span>Returned</span>]);return <Page title="Issues / Returns"><form className="form-grid panel" onSubmit={issue}><select value={form.bookId} onChange={e=>setForm({...form,bookId:e.target.value})} required><option value="">Book</option>{books.filter(b=>b.availableCopies>0).map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select><select value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})} required><option value="">Student</option>{users.filter(u=>u.role==='STUDENT').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><input type="date" value={form.issueDate} onChange={e=>setForm({...form,issueDate:e.target.value})}/><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})} required/><button className="primary">Issue Book</button></form><Table headers={['ID','Book','Student','Issue Date','Due Date','Return','Action']} rows={rows}/></Page>}

function Fines({fines,users,books,user,create,update,del}){const [form,setForm]=useState({studentId:'',bookId:'',overdueDays:1,amount:5,status:'PENDING'});const save=async e=>{e.preventDefault();await create('/fines',{...form,studentId:+form.studentId,bookId:+form.bookId,overdueDays:+form.overdueDays,amount:+form.amount});};const rows=fines.filter(f=>user.role==='STUDENT'?f.studentId===user.id:true).map(f=>[f.id,f.studentName||f.student?.name,f.bookTitle||f.book?.title,f.overdueDays,`₹${f.amount}`,f.status,user.role!=='STUDENT'?<><button className="small" onClick={()=>update(`/fines/${f.id}`,{...f,status:'PAID'})}>Mark Paid</button> <button className="small danger" onClick={()=>del(`/fines/${f.id}`)}>Delete</button></>:<span>View</span>]);return <Page title="Fines / Penalties">{user.role!=='STUDENT'&&<form className="form-grid panel" onSubmit={save}><select value={form.studentId} onChange={e=>setForm({...form,studentId:e.target.value})} required><option value="">Student</option>{users.filter(u=>u.role==='STUDENT').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><select value={form.bookId} onChange={e=>setForm({...form,bookId:e.target.value})} required><option value="">Book</option>{books.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select><input type="number" min="1" value={form.overdueDays} onChange={e=>setForm({...form,overdueDays:+e.target.value,amount:+e.target.value*5})}/><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:+e.target.value})}/><button className="primary">Create Fine</button></form>}<Table headers={['ID','Student','Book','Days','Amount','Status','Action']} rows={rows}/></Page>}

function Payments({payments,fines,users,user,create,update,del}){const pending=fines.filter(f=>f.status!=='PAID'&&(user.role!=='STUDENT'||f.studentId===user.id));const [form,setForm]=useState({fineId:'',method:'UPI',reference:''});const pay=async e=>{e.preventDefault();await create('/payments',{...form,fineId:+form.fineId,paidAt:new Date().toISOString(),status:'SUCCESS'});setForm({...form,fineId:'',reference:''})};const rows=payments.filter(p=>user.role==='STUDENT'?p.studentId===user.id:true).map(p=>[p.id,p.studentName||p.student?.name,p.amount?`₹${p.amount}`:'—',p.method,p.reference,p.status,new Date(p.paidAt).toLocaleDateString()]);return <Page title="Payments">{pending.length>0&&<form className="form-grid panel" onSubmit={pay}><select value={form.fineId} onChange={e=>setForm({...form,fineId:e.target.value})} required><option value="">Select fine</option>{pending.map(f=><option key={f.id} value={f.id}>#{f.id} — ₹{f.amount}</option>)}</select><select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option>UPI</option><option>Credit Card</option><option>Debit Card</option><option>Net Banking</option></select><input placeholder="Payment reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} required/><button className="primary">Pay (Demo)</button></form>}<Table headers={['ID','Student','Amount','Method','Reference','Status','Date']} rows={rows}/></Page>}

function Table({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">No records found.</td></tr>}</tbody></table></div>}

createRoot(document.getElementById('root')).render(<App />)
